#!/bin/sh
set -e

source secrets

if ! carina get howtowhale-dev; then
  carina create --wait --template "Swarm 1.11.2 on LXC" howtowhale-dev
fi
carina credentials howtowhale-dev
eval $(carina env howtowhale-dev)
dvm use

echo "Add an A record to your DNS now pointing to the IP address below:"
docker run --rm --net=host -e constraint:node==*master* racknet/ip public ipv4
read -p "Press ENTER to continue"

docker run \
  --name letsencrypt-data \
  --volume /etc/letsencrypt \
  --volume /var/lib/letsencrypt \
  --entrypoint /bin/mkdir \
  quay.io/letsencrypt/letsencrypt \
  -p /etc/letsencrypt/webrootauth/

docker run \
  --rm --interactive --tty \
  --volumes-from letsencrypt-data \
  nginx \
  openssl dhparam -out /etc/letsencrypt/dhparams.pem 2048

docker run \
  --rm \
  --volumes-from letsencrypt-data \
  --publish 443:443 \
  --publish 80:80 \
  quay.io/letsencrypt/letsencrypt certonly \
  --server https://acme-v01.api.letsencrypt.org/directory \
  --domain dev.howtowhale.com \
  --authenticator standalone \
  --email me@carolynvanslyck.com \
  --agree-tos
