#!/bin/sh
set -e

source secrets

eval $(carina env howtowhale-prod)
dvm use

read -r BASE_FROM < howtowhale-user/Dockerfile
BASE_TAG=${BASE_FROM#*:}
VERSION=$(git describe)

echo "### Cleanup from previous runs"
docker ps -qa --filter="name=howtowhale" | xargs docker rm -vf

echo "### Build the user's notebook server"
docker build -t carolynvs/howtowhale-user:$VERSION howtowhale-user/
docker push carolynvs/howtowhale-user:$VERSION

echo "### Run the static site"
docker build -t carolynvs/howtowhale-web:$VERSION howtowhale-web/
docker run --name howtowhale-web carolynvs/howtowhale-web:$VERSION

echo "### Build the hub"
docker build -t carolynvs/howtowhale-hub:$VERSION \
  howtowhale-hub/
docker build -t carolynvs/howtowhale-proxy \
  --build-arg domain=howtowhale.com \
  --build-arg affinity:container==letsencrypt-data \
  howtowhale-proxy/

echo "### Spin up the hub"
docker run --name howtowhale-hub \
  -d -p 8081:8081 \
  --restart always \
  --volumes-from swarm-data:ro \
  -e VERSION=$VERSION \
  -e DOMAIN=howtowhale.com \
  -e CARINA_OAUTH_HOST=oauth.getcarina.com \
  -e CARINA_CLIENT_ID=$CARINA_CLIENT_ID \
  -e CARINA_CLIENT_SECRET=$CARINA_CLIENT_SECRET \
  -e DOCKER_HOST=https://${DOCKER_HOST#tcp://} \
  -e JPY_COOKIE_SECRET=$JPY_COOKIE_SECRET \
  -e DB_HOST=$DB_HOST \
  -e DB_NAME=$DB_NAME \
  -e DB_USERNAME=$DB_NAME \
  -e DB_PASSWORD=$DB_PASSWORD \
  carolynvs/howtowhale-hub:$VERSION

echo "### Spin up the proxy"
docker run --name howtowhale-proxy \
  -d -p 80:80 -p 443:443 \
  --restart always \
  --link howtowhale-hub:howtowhale-hub \
  --volumes-from letsencrypt-data \
  --volumes-from howtowhale-web \
  carolynvs/howtowhale-proxy
