#!/bin/sh
set -e

source secrets

eval $(carina env howtowhale-prod)
dvm use

read -r BASE_FROM < howtowhale-user/Dockerfile
BASE_TAG=${BASE_FROM#*:}
VERSION=$(git describe --dirty='-dev')

echo "### Cleanup from previous runs"
docker ps -qa --filter="name=howtowhale" | xargs docker rm -vf

echo "### Build a minimal notebook server"
docker build -t carolynvs/minimal-notebook:$BASE_TAG -f howtowhale-user/Dockerfile.minimal-notebook howtowhale-user/
docker push carolynvs/minimal-notebook:$BASE_TAG

echo "### Build the user's notebook server"
docker build -t carolynvs/howtowhale-user:$VERSION howtowhale-user/
docker push carolynvs/howtowhale-user:$VERSION

echo "### Build the hub"
docker build -t carolynvs/howtowhale-hub:$VERSION \
  --build-arg version=$VERSION \
  --build-arg domain=howtowhale.com \
  howtowhale-hub/
docker build -t carolynvs/howtowhale-proxy \
  --build-arg domain=howtowhale.com \
  --build-arg affinity:container==letsencrypt-data \
  howtowhale-proxy/

echo "### Spin up the hub"
docker run --name howtowhale-hub \
  -d -p 8081:8081 \
  --volumes-from swarm-data:ro \
  -e CARINA_OAUTH_HOST=oauth.getcarina.com \
  -e CARINA_CLIENT_ID=$CARINA_CLIENT_ID \
  -e CARINA_CLIENT_SECRET=$CARINA_CLIENT_SECRET \
  -e DOCKER_HOST=https://${DOCKER_HOST#tcp://} \
  carolynvs/howtowhale-hub:$VERSION

echo "### Spin up the proxy"
docker run --name howtowhale-proxy \
  -d -p 80:80 -p 443:443 \
  --link howtowhale-hub:howtowhale-hub \
  --volumes-from letsencrypt-data \
  carolynvs/howtowhale-proxy

echo "# Cleanup my test user"
eval $(carina env howtowhale)
docker ps -qa --filter="name=howtowhale-carolynvs" | xargs docker rm -vf
