#!/bin/sh


docker ps -qa --filter="name=howtowhale" | xargs docker rm -vf

docker build -t carolynvs/howtowhale-user howtowhale-user/
docker push carolynvs/howtowhale-user
docker build -t carolynvs/howtowhale-hub howtowhale-hub/
# use --build-arg affinity:container==letsencrypt-data  if we grow the cluster
docker build -t carolynvs/howtowhale-proxy howtowhale-proxy/

docker run --name howtowhale-hub \
  -d -p 8081:8081 \
  --volumes-from swarm-data:ro \
  -e CARINA_OAUTH_HOST=https://carina-oauth.carolynvs.com \
  -e DOCKER_HOST=https://${DOCKER_HOST#tcp://} \
  carolynvs/howtowhale-hub

#HUB_INTERNAL_IP=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' howtowhale-hub)

docker run --name howtowhale-proxy \
  -d --link howtowhale-hub:howtowhale-hub -p 80:80 -p 443:443 \
  --volumes-from letsencrypt-data \
  carolynvs/howtowhale-proxy
